import {
  TrendingUp, Brain, Shield, Zap, BarChart2, Clock,
  Telescope, Users, MessageSquare, CloudCog,
} from 'lucide-react'

export const NEW_FEATURES = [
  {
    icon:   <MessageSquare className="text-blue-400" size={24} />,
    badge:  'New',
    title:  'Unified Alex Chat',
    desc:   'Single interface with automatic routing across chat, research, SEC analysis, and specialist agents.',
    ai:     ['intent router', 'tool agents', 'specialist handoff', 'live streaming'],
    stack:  ['Amazon Nova', 'Bedrock SSE', 'yfinance', 'EdgarTools'],
    href:   '/research',
    accent: 'border-blue-500/30 bg-blue-500/5',
    theme:  'blue' as const,
  },
  {
    icon:   <Users className="text-amber-400" size={24} />,
    badge:  'New',
    title:  'Trading Floor',
    desc:   'Multi-agent debate on portfolio positions with logged votes and simulated trade rationale.',
    ai:     ['multi-agent debate', 'bull vs bear votes', 'risk scoring', 'simulated trades'],
    stack:  ['5 LLM personas', 'parallel agents', 'Aurora logs', 'SQS queue'],
    href:   '/trading',
    accent: 'border-amber-500/30 bg-amber-500/5',
    theme:  'amber' as const,
  },
  {
    icon:   <Telescope className="text-indigo-400" size={24} />,
    badge:  'New',
    title:  'Observe',
    desc:   'Query-level observability for latency, tool execution, guardrails, and token usage.',
    ai:     ['query tracing', 'tool pass/fail', 'guardrail hits', 'token costs'],
    stack:  ['Aurora metrics', 'CloudWatch', 'per-prompt logs'],
    href:   '/observe',
    accent: 'border-indigo-500/30 bg-indigo-500/5',
    theme:  'indigo' as const,
  },
  {
    icon:   <CloudCog className="text-emerald-400" size={24} />,
    badge:  'New',
    title:  'AWS Cost Agent',
    desc:   'Operational spend and service health on your dashboard, refreshed every 30 minutes.',
    ai:     ['ops agent', 'spend digests', 'health checks'],
    stack:  ['Cost Explorer', 'Lambda 30min', 'live dashboard widget'],
    href:   '/dashboard#ops-cost',
    accent: 'border-emerald-500/30 bg-emerald-500/5',
    theme:  'emerald' as const,
  },
]

export const CORE_FEATURES = [
  {
    icon:  <Clock className="text-blue-400" size={24} />,
    title: '24/7 Autonomous Research',
    desc:  'Scheduled portfolio digests every two hours.',
    ai:    ['planner agent', 'auto digests', 'sentiment tags'],
    stack: ['EventBridge', 'SQS pipeline', 'Lambda agents'],
    theme: 'blue' as const,
  },
  {
    icon:  <Brain className="text-purple-400" size={24} />,
    title: 'Per-User Memory (RAG)',
    desc:  'Session-scoped vector memory for research continuity.',
    ai:    ['RAG memory', 'session context', 'similarity search'],
    stack: ['pgvector', 'SageMaker embeds', 'Aurora'],
    theme: 'purple' as const,
  },
  {
    icon:  <Shield className="text-green-400" size={24} />,
    title: 'Layered Guardrails',
    desc:  'Policy and safety controls with full audit logging.',
    ai:    ['policy router', 'Bedrock guardrails', 'block logging'],
    stack: ['regex + LLM gate', 'safety filters'],
    theme: 'green' as const,
  },
  {
    icon:  <TrendingUp className="text-yellow-400" size={24} />,
    title: 'Real Market Data',
    desc:  'Live prices, SEC filings, and tool-augmented web research.',
    ai:    ['tool-augmented answers', 'SEC parsing', 'web browse'],
    stack: ['yfinance API', 'EdgarTools', 'Playwright MCP'],
    theme: 'yellow' as const,
  },
  {
    icon:  <BarChart2 className="text-red-400" size={24} />,
    title: 'Multi-Agent Pipeline',
    desc:  'Coordinated planner, tagger, and reporter agents via SQS.',
    ai:    ['task split', 'parallel research', 'merge results'],
    stack: ['planner / tagger / reporter', 'map-reduce agents'],
    theme: 'red' as const,
  },
  {
    icon:  <Zap className="text-orange-400" size={24} />,
    title: 'Tiered Model Routing',
    desc:  'Nova Lite for routine queries; Nova Pro for deep analysis.',
    ai:    ['auto route pick', 'Nova Lite vs Pro', 'cost-aware'],
    stack: ['query classifier', 'tiered LLMs'],
    theme: 'orange' as const,
  },
]
