import {
  TrendingUp, Brain, Shield, Zap, BarChart2, Clock,
  Telescope, Users, MessageSquare, CloudCog,
} from 'lucide-react'

export const NEW_FEATURES = [
  {
    icon:   <MessageSquare className="text-blue-400" size={24} />,
    badge:  'New',
    title:  'Unified Alex Chat',
    desc:   'One chat box. Alex auto-routes to chat, fast research, deep SEC analysis, or specialist debater handoff. No manual mode toggle. Streaming markdown tables, news links, and smooth scroll UX.',
    ai:     ['intent router', 'tool agents', 'specialist handoff', 'live streaming'],
    stack:  ['Amazon Nova', 'Bedrock SSE', 'yfinance', 'EdgarTools'],
    href:   '/research',
    accent: 'border-blue-500/30 bg-blue-500/5',
    theme:  'blue' as const,
  },
  {
    icon:   <Users className="text-amber-400" size={24} />,
    badge:  'New',
    title:  'Trading Floor',
    desc:   'Five named agents (Marcus, Victoria, Zara, Reid, Elena) debate your holdings in parallel and record every vote. Paper-trades with full bull/bear/risk reasoning visible in the UI.',
    ai:     ['multi-agent debate', 'bull vs bear votes', 'risk scoring', 'simulated trades'],
    stack:  ['5 LLM personas', 'parallel agents', 'Aurora logs', 'SQS queue'],
    href:   '/trading',
    accent: 'border-amber-500/30 bg-amber-500/5',
    theme:  'amber' as const,
  },
  {
    icon:   <Telescope className="text-indigo-400" size={24} />,
    badge:  'New',
    title:  'Observe',
    desc:   'Production AI observability: per-query latency, tool/MCP pass-fail, guardrail hits, and agent token costs. See exactly what Alex did on every prompt, not a black box.',
    ai:     ['query tracing', 'tool pass/fail', 'guardrail hits', 'token costs'],
    stack:  ['Aurora metrics', 'CloudWatch', 'per-prompt logs'],
    href:   '/observe',
    accent: 'border-indigo-500/30 bg-indigo-500/5',
    theme:  'indigo' as const,
  },
  {
    icon:   <CloudCog className="text-emerald-400" size={24} />,
    badge:  'New',
    title:  'AWS Cost Agent',
    desc:   'Live ops dashboard widget: today, week, and MTD AWS spend with service breakdown and 7-service health score. Cost Explorer data refreshed every 30 minutes on your dashboard.',
    ai:     ['ops agent', 'spend digests', 'health checks'],
    stack:  ['Cost Explorer', 'Lambda 30min', 'live dashboard widget'],
    href:   '/dashboard#ops-cost',
    accent: 'border-emerald-500/30 bg-emerald-500/5',
    theme:  'emerald' as const,
  },
]

export const CORE_FEATURES = [
  {
    icon:  <Clock className="text-blue-400" size={24} />,
    title: '24/7 Autonomous Research',
    desc:  'Scheduled workflows generate portfolio digests every 2 hours. No prompting required.',
    ai:    ['planner agent', 'auto digests', 'sentiment tags'],
    stack: ['EventBridge', 'SQS pipeline', 'Lambda agents'],
    theme: 'blue' as const,
  },
  {
    icon:  <Brain className="text-purple-400" size={24} />,
    title: 'Per-User Memory (RAG)',
    desc:  'pgvector knowledge base scoped to your sessions. Alex remembers your research history.',
    ai:    ['RAG memory', 'session context', 'similarity search'],
    stack: ['pgvector', 'SageMaker embeds', 'Aurora'],
    theme: 'purple' as const,
  },
  {
    icon:  <Shield className="text-green-400" size={24} />,
    title: 'Layered Guardrails',
    desc:  'Off-topic blocks, policy flags, and Bedrock safety. Every guardrail logged to Observe.',
    ai:    ['policy router', 'Bedrock guardrails', 'block logging'],
    stack: ['regex + LLM gate', 'safety filters'],
    theme: 'green' as const,
  },
  {
    icon:  <TrendingUp className="text-yellow-400" size={24} />,
    title: 'Real Market Data',
    desc:  'yfinance live prices, EdgarTools SEC filings, and Playwright MCP for deep web research.',
    ai:    ['tool-augmented answers', 'SEC parsing', 'web browse'],
    stack: ['yfinance API', 'EdgarTools', 'Playwright MCP'],
    theme: 'yellow' as const,
  },
  {
    icon:  <BarChart2 className="text-red-400" size={24} />,
    title: 'Multi-Agent Pipeline',
    desc:  'Planner, Tagger, and Reporter agents coordinate via SQS for parallel comparative analysis.',
    ai:    ['task split', 'parallel research', 'merge results'],
    stack: ['planner / tagger / reporter', 'map-reduce agents'],
    theme: 'red' as const,
  },
  {
    icon:  <Zap className="text-orange-400" size={24} />,
    title: 'Tiered Model Routing',
    desc:  'Nova Lite for chat and fast lookups. Nova Pro for deep research. Cost-efficient by design.',
    ai:    ['auto route pick', 'Nova Lite vs Pro', 'cost-aware'],
    stack: ['query classifier', 'tiered LLMs'],
    theme: 'orange' as const,
  },
]
